# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time

from PyQt5 import QtCore, QtGui, QtWidgets
import Camera

class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 600)
        Form.setMinimumSize(QtCore.QSize(1200, 600))
        Form.setMaximumSize(QtCore.QSize(1200, 600))

        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1200, 600))
        self.tabWidget.setMinimumSize(QtCore.QSize(1200, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(1200, 600))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setMinimumSize(QtCore.QSize(1200, 600))
        self.tab.setMaximumSize(QtCore.QSize(1200, 600))
        self.tab.setObjectName("tab")

        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(0, 0, 890, 540))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(900, 20, 60, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(900, 60, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(900, 100, 60, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(970, 20, 121, 16))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(990, 60, 121, 16))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(990, 100, 121, 16))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QtCore.QRect(0, 550, 60, 16))
        self.label_12.setText("Status: ")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QtCore.QRect(60, 550, 221, 16))
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QtCore.QRect(930, 150, 241, 181))

        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(1070, 530, 113, 32))
        self.pushButton.setObjectName("pushButton")
        #self.pushButton.setGeometry(QtCore.QRect(940, 530, 113, 32))
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QtCore.QRect(940, 530, 113, 32))

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 890, 540))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(900, 10, 60, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(900, 40, 60, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(900, 70, 60, 16))
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QtCore.QRect(10, 540, 60, 16))
        self.label_14.setText("Status: ")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QtCore.QRect(70, 540, 311, 16))

        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(982, 10, 201, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(982, 40, 201, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(982, 70, 201, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")


        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(1070, 520, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(1070, 110, 113, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab_2, "")

        # self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        # self.textEdit.setObjectName(u"textEdit")
        # self.textEdit.setGeometry(QtCore.QRect(430, 240, 181, 21))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.func()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("CAMERA", "CAMERA"))
        self.label.setText(_translate("Form", "Camera"))
        self.label_2.setText(_translate("Form", "Name"))
        self.label_3.setText(_translate("Form", "Surname"))
        self.label_4.setText(_translate("Form", "Group"))
        self.pushButton.setText(_translate("Form", "Close"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CAMERA", "MAIN"))
        self.label_8.setText(_translate("Form", "Camera"))
        self.label_9.setText(_translate("Form", "Name"))
        self.label_10.setText(_translate("Form", "Surname"))
        self.label_11.setText(_translate("Form", "Group"))
        self.pushButton_2.setText(_translate("Form", "Close"))
        self.pushButton_3.setText(_translate("Form", "Enter"))
        self.pushButton_4.setText(_translate("Form", "FIND"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("CAMERA", "SAVE"))

        self.pushButton_2.clicked.connect(Form.close)
        self.pushButton.clicked.connect(Form.close)

    def func(self):
        self.pushButton_3.clicked.connect(self.fun_read)
        self.pushButton_4.clicked.connect(self.fun_show)

    def fun_read(self):
        name = self.lineEdit.text()
        surname = self.lineEdit_2.text()
        group = self.lineEdit_3.text()
        Camera.SaveNew(name, surname, group).save_photo()

    def fun_show(self):
        Camera.SaveNew.show_profile()

# if __name__ == '__main__':
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
